In [3]:
import numpy as np

In [2]:
numpy.__version__

'1.18.5'

In [4]:
a1 = np.array([2,3,4,5] )
#array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

In [5]:
print(a1)

[2 3 4 5]


In [10]:
print(a1.shape)
print(a1.size)
print(a1.ndim)
print(a1.dtype)

(4,)
4
1
int64


In [22]:
a2 = np.array(
    [ 
     [2,3,4,5] ,
     [6,7,8,9] 
    ])

In [12]:
print(a2.shape)
print(a2.size)
print(a2.ndim)
print(a2.dtype)

(2, 4)
8
2
float64


In [16]:
print( np.ones((2,3)) )
print( np.zeros((2,3,2)) )

[[1. 1. 1.]
 [1. 1. 1.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [27]:
print(a2)
print("\na2[0,0]   ", a2[0,0])
print("a2[1,2]   ", a2[1,2])
print("a2[1]     ", a2[1])
print("a2[0,1:3] ", a2[0,1:3]) #slice
print("a2[0:2,1:3] ", a2[0:2,1:3])

[[2 3 4 5]
 [6 7 8 9]]

a2[0,0]    2
a2[1,2]    8
a2[1]      [6 7 8 9]
a2[0,1:3]  [3 4]
a2[0:2,1:3]  [[3 4]
 [7 8]]


In [33]:
a3 = np.arange(8)
print(a3)
print(a3[1:5])
print(a3[:5])
print(a3[3:])
print(a3[:])

[0 1 2 3 4 5 6 7]
[1 2 3 4]
[0 1 2 3 4]
[3 4 5 6 7]
[0 1 2 3 4 5 6 7]


In [34]:
# change the data
print(a3)
a3[4] = 90
print(a3)

[0 1 2 3 4 5 6 7]
[ 0  1  2  3 90  5  6  7]


In [41]:

a3 = np.arange(8)
print(a3)
a3[2:5] = 9
print(a3)
a3[2:5] = [9,99,199]
print(a3)
#a3[2:5] = [9,99,199,299,399,499]
#a3[2:5] = [9,99 ]
a3[2:5] = [9,99,10.10]
print(a3)

[0 1 2 3 4 5 6 7]
[0 1 9 9 9 5 6 7]
[  0   1   9  99 199   5   6   7]
[ 0  1  9 99 10  5  6  7]


In [48]:
a4 = np.arange(12)
print(a4)
a4 = a4.reshape(3,4)
print(a4)
print("\na4[0:2 , 1:3]  ", a4[0:2 , 1:3])
print("\na4[: , 1:3]  ", a4[: , 1:3])  

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a4[0:2 , 1:3]   [[1 2]
 [5 6]]

a4[: , 1:3]   [[ 1  2]
 [ 5  6]
 [ 9 10]]


In [58]:
a4 = np.arange(24)
print(a4)
a4 = a4.reshape(3,4,2)
print(a4)
print (a4[:, 1:3 , 1])
# for non contigous
print (a4[:, [1,3] , 1])
print (a4[:,: , [1]])
print (a4[..., 1])

SyntaxError: ignored