In [30]:
#3d arrays
import numpy as np
earnings = [
 [ [500,505,490], [810,450,678], [234,897,430], [560,1023,640] ], 
[ [600,605,490], [345,900,1000], [780,730,710], [670,540,324] ] 
]
earnings = np.array(earnings) 
print(earnings[0,0,0])

earnings.shape


500


(2, 4, 3)

In [13]:
#to get the earnings for January of all years

print(earnings[:,0,0])

#to get first quarter earnings from both years

earnings[:,0,:]


[500 600]


array([[500, 505, 490],
       [600, 605, 490]])

In [14]:
#why broadcasting?
#this works but not good for large arrays

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [43]:
#an alternative with tile by stacking multiple copies of v vertically
import numpy as np

# We will add the vector v to each row of the matrix x,1
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4,1 ))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
print("------\n")                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
------

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [39]:
#Numpy broadcasting allows us to perform this computation without actually creating 
#multiple copies of v. 
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"
            #The line y = x + v works even though x has shape (4, 3) and v has shape (3,)
            #due to broadcasting; this line works as if v actually had shape (4, 3), 
            #where each row was a copy of v, and the sum was performed elementwise


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [17]:
#Application of broadcasting
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


In [21]:
#reduce example
#A multi-dimensional array example:

X = np.arange(8).reshape((2,2,2))
X
#array([[[0, 1],
 #       [2, 3]],
  #     [[4, 5],
   #     [6, 7]]])
np.add.reduce(X, 0)
#array([[ 4,  6],
#[ 8, 10]])
np.add.reduce(X) # confirm: default axis value is 0
np.add.reduce(X, 1)
#array([[ 2,  4],
#      [10, 12]])
np.add.reduce(X, 2)


array([[ 1,  5],
       [ 9, 13]])

In [29]:
import numpy as np
a=np.array([500,505,490,810,450,678,234,897,430,560,1023,640])
year_one = [ [500,505,490], [810,450,678], [234,897,430], [560,1023,640] ]
year_one[0][0]
year_one[0]
             
             


[500, 505, 490]