In [1]:
import numpy as np

In [2]:
np.arange (4)

array([0, 1, 2, 3])

In [3]:
A = np.arange (10)

In [4]:
print (A)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
B = np.random.random(10)

In [6]:
print (B)

[ 0.03542612  0.6633247   0.37075662  0.90892315  0.14453036  0.89995415
  0.56254368  0.68535778  0.46996552  0.45749111]


In [7]:
print (B*2)

[ 0.07085223  1.32664941  0.74151323  1.81784629  0.28906073  1.79990831
  1.12508735  1.37071556  0.93993104  0.91498222]


In [8]:
B>.5

array([False,  True, False,  True, False,  True,  True,  True, False, False], dtype=bool)

In [11]:
print(B.shape)

(10,)


In [12]:
print (A)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
A.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
np.arange(10).reshape(5,6)

ValueError: cannot reshape array of size 10 into shape (5,6)

In [14]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
C = np.array([180,80,10],[158,55,7] ,[210,110,14])

ValueError: only 2 non-keyword arguments accepted

In [19]:
C = np.array([[180,80,10],[158,55,7] ,[210,110,14]])

In [20]:
print (C)

[[180  80  10]
 [158  55   7]
 [210 110  14]]


In [21]:
D = np.arange(10,20,2)

In [22]:
print (D
      )

[10 12 14 16 18]


In [24]:
print ("C array is ", C, " Max of  C ", C.max())

C array is  [[180  80  10]
 [158  55   7]
 [210 110  14]]  Max of  C  210


In [25]:
print (" Max of  C ", C.sum())

 Max of  C  824


In [26]:
C.sum

<function ndarray.sum>

In [28]:
C.dtype

dtype('int32')

In [29]:
C.shape

(3, 3)

In [30]:
C.sum

<function ndarray.sum>

In [31]:
C.sum()

824

In [32]:
print(C)

[[180  80  10]
 [158  55   7]
 [210 110  14]]


In [33]:
C(1,1)

TypeError: 'numpy.ndarray' object is not callable

In [35]:
print(C[1,1])

55


In [36]:
print (C)

[[180  80  10]
 [158  55   7]
 [210 110  14]]


In [37]:
C[1,:] #all columns having row aas 1

array([158,  55,   7])

In [38]:
C[:,1] #all row but column should be 1

array([ 80,  55, 110])

In [39]:
C[:1,2]

array([10])

In [40]:
C[:2,2] #all rows below rowid 2 ie. 0,1 and column has to be 2

array([10,  7])

In [41]:
#show only height of all
C[:,0]

array([180, 158, 210])

In [42]:
print (C )

[[180  80  10]
 [158  55   7]
 [210 110  14]]


In [43]:
C[1:,1:]

array([[ 55,   7],
       [110,  14]])

In [44]:
C[...,1]

array([ 80,  55, 110])

In [45]:
C[:,1]

array([ 80,  55, 110])

In [46]:
print(C)

[[180  80  10]
 [158  55   7]
 [210 110  14]]


In [47]:
print (C.T)

[[180 158 210]
 [ 80  55 110]
 [ 10   7  14]]
