In [3]:
import math

In [5]:
math.sqrt(4)

2.0

In [6]:
import math as m

In [7]:
m.sqrt(4)

2.0

In [8]:
from math import sqrt

In [9]:
sqrt(4)

2.0

In [10]:
import numpy as np

In [11]:
a = np.array([1,2,3,4])

In [12]:
a

array([1, 2, 3, 4])

In [14]:
aa = np.array([[ 1,2,3,4] , [9,8,7,6]])

In [15]:
aa

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [16]:
aa[1,3]

6

In [17]:
aa[1,3] = 80

In [18]:
aa

array([[ 1,  2,  3,  4],
       [ 9,  8,  7, 80]])

In [19]:
aa.size

8

In [20]:
aa.ndim

2

In [21]:
aa.shape

(2, 4)

In [22]:
aa.dtype

dtype('int32')

In [23]:
type (aa)

numpy.ndarray

In [24]:
a

array([1, 2, 3, 4])

In [25]:
aa

array([[ 1,  2,  3,  4],
       [ 9,  8,  7, 80]])

In [26]:
a+4

array([5, 6, 7, 8])

In [27]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [28]:
   a 

array([1, 2, 3, 4])

In [29]:
a+=1

In [30]:
a

array([2, 3, 4, 5])

In [32]:
a.max()

5

In [36]:
a1 = a**2

In [39]:
a

array([2, 3, 4, 5])

In [40]:
a.cumsum()

array([ 2,  5,  9, 14], dtype=int32)

In [41]:
a+a1

array([ 6, 12, 20, 30])

In [42]:
aa

array([[ 1,  2,  3,  4],
       [ 9,  8,  7, 80]])

In [43]:
aa.max()

80

In [44]:
aa[0:1,1]

array([2])

In [47]:
aa[:,1]

array([2, 8])

In [48]:
aa[:,2]

array([3, 7])

In [49]:
aa[1,:]

array([ 9,  8,  7, 80])

In [50]:
aa[1,1:3]

array([8, 7])

In [51]:
a

array([2, 3, 4, 5])

In [53]:
aa>3

array([[False, False, False,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [57]:
for i in range (len(aa)):
    print (aa[i])

[1 2 3 4]
[ 9  8  7 80]


In [58]:
aa

array([[ 1,  2,  3,  4],
       [ 9,  8,  7, 80]])

In [59]:
aa[1,:]

array([ 9,  8,  7, 80])

In [60]:
aa1 = np.array([[1,2], [2,3]])
aa2  = np.array([[2,3], [4,3]])

In [61]:
aa1*aa2

array([[2, 6],
       [8, 9]])

In [62]:
aa1.dot(aa2)

array([[10,  9],
       [16, 15]])