In [3]:
import math

In [5]:
math.sqrt(4)

2.0

In [6]:
import math as m

In [7]:
m.sqrt(4)

2.0

In [8]:
from math import sqrt

In [9]:
sqrt(4)

2.0

In [10]:
import numpy as np

In [11]:
a = np.array([1,2,3,4])

In [12]:
a

array([1, 2, 3, 4])

In [14]:
aa = np.array([[ 1,2,3,4] , [9,8,7,6]])

In [15]:
aa

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [16]:
aa[1,3]

6

In [17]:
aa[1,3] = 80

In [18]:
aa

array([[ 1,  2,  3,  4],
       [ 9,  8,  7, 80]])

In [19]:
aa.size

8

In [20]:
aa.ndim

2

In [21]:
aa.shape

(2, 4)

In [22]:
aa.dtype

dtype('int32')

In [23]:
type (aa)

numpy.ndarray

In [24]:
a

array([1, 2, 3, 4])

In [25]:
aa

array([[ 1,  2,  3,  4],
       [ 9,  8,  7, 80]])

In [26]:
a+4

array([5, 6, 7, 8])

In [27]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [28]:
   a 

array([1, 2, 3, 4])

In [29]:
a+=1

In [30]:
a

array([2, 3, 4, 5])

In [32]:
a.max()

5

In [36]:
a1 = a**2

In [39]:
a

array([2, 3, 4, 5])

In [40]:
a.cumsum()

array([ 2,  5,  9, 14], dtype=int32)

In [41]:
a+a1

array([ 6, 12, 20, 30])

In [42]:
aa

array([[ 1,  2,  3,  4],
       [ 9,  8,  7, 80]])

In [43]:
aa.max()

80

In [44]:
aa[0:1,1]

array([2])

In [47]:
aa[:,1]

array([2, 8])

In [48]:
aa[:,2]

array([3, 7])

In [49]:
aa[1,:]

array([ 9,  8,  7, 80])

In [50]:
aa[1,1:3]

array([8, 7])

In [51]:
a

array([2, 3, 4, 5])

In [53]:
aa>3

array([[False, False, False,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [57]:
for i in range (len(aa)):
    print (aa[i])

[1 2 3 4]
[ 9  8  7 80]


In [58]:
aa

array([[ 1,  2,  3,  4],
       [ 9,  8,  7, 80]])

In [59]:
aa[1,:]

array([ 9,  8,  7, 80])

In [60]:
aa1 = np.array([[1,2], [2,3]])
aa2  = np.array([[2,3], [4,3]])

In [61]:
aa1*aa2

array([[2, 6],
       [8, 9]])

In [62]:
aa1.dot(aa2)

array([[10,  9],
       [16, 15]])

In [8]:
import numpy as np
a=np.ones( (2,4), dtype=np.int16 )

In [10]:
print(a)

[[1 1 1 1]
 [1 1 1 1]]


In [29]:
a = np.arange(50,74,)

In [30]:
a

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73])

In [31]:
b=a.reshape(2,3,4)

In [32]:
b

array([[[50, 51, 52, 53],
        [54, 55, 56, 57],
        [58, 59, 60, 61]],

       [[62, 63, 64, 65],
        [66, 67, 68, 69],
        [70, 71, 72, 73]]])

In [36]:
c=b-50
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
c>10

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]], dtype=bool)

In [38]:
c%5

array([[[0, 1, 2, 3],
        [4, 0, 1, 2],
        [3, 4, 0, 1]],

       [[2, 3, 4, 0],
        [1, 2, 3, 4],
        [0, 1, 2, 3]]], dtype=int32)

In [42]:
# print/true all elements of array c having value>10 and value<20
(c>10) and (c<20)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [48]:
c[((c>10) and (c<20)) ]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [49]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [50]:
c.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [55]:
a1=np.arange(6).reshape(3,2)

In [56]:
a1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [57]:
a2= np.arange(4).reshape(2,2)
a2

array([[0, 1],
       [2, 3]])

In [58]:
a1+a2

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [1]:
import numpy as np

In [2]:
help(np.genfromtxt)

Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings in Python 3k.  The strings
        in a list or 

In [18]:
heightdata = np.genfromtxt('data/president_heights.csv',delimiter=',',skip_header=1)

In [20]:
#last row from heightdata
heights=heightdata [:,2]

In [21]:
print (heights)

[ 189.  170.  189.  163.  183.  171.  185.  168.  173.  183.  173.  173.
  175.  178.  183.  193.  178.  173.  174.  183.  183.  168.  170.  178.
  182.  180.  183.  178.  182.  188.  175.  179.  183.  193.  182.  183.
  177.  185.  188.  188.  182.  185.]


In [23]:
heights.max()

193.0

In [24]:
heights.min()

163.0

In [25]:
heights.mean()

179.73809523809524

In [26]:
heights.sum()

7549.0

In [27]:
sum(heights)

7549.0

In [28]:
%timeit heights.sum()

1.44 µs ± 24.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [29]:
%timeit sum(heights)

3.94 µs ± 191 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [33]:
import csv
with open('data/president_heights.csv','r') as f:
    pdataList = list(csv.reader(f ,delimiter=',') )

In [50]:
pdataList[:,1:]

TypeError: list indices must be integers or slices, not tuple

In [57]:
pdataList[:][:][2]

['2', 'John Adams', '170']

In [58]:
pdataList[:][0:10][2]

['2', 'John Adams', '170']