i.	Write a program to print all Armstrong numbers in a given range. Note: An Armstrong number is a number whose sum of cubes of digits is equal to the number itself. E.g. 370=33+73+03

In [0]:
# take input from the user
lower = int(input("Enter lower range: "))
upper = int(input("Enter upper range: "))
 
for num in range(lower,upper + 1):
   # initialize sum
   sum = 0
 
   # find the sum of the cube of each digit
   temp = num
   while temp > 0:
       digit = temp % 10
       sum += digit ** 3
       temp //= 10
 
   if num == sum:
       print(num)


Enter lower range: 100
Enter upper range: 300
153


ii.	Write a function to obtain sum n terms of the following series for any positive integer value of X 
X +X3 /3! +X5 /5! ! +X7 /7! + … 


In [0]:
def fact(num):
    f=1
    for s in range (1,num+1):
        f=f*s
    return f


n=int(input("enter value of n:"))
x= int(input("enter value of x:"))

i=1
s=0
j=1
while j<=n:
    p=pow(x,i)
    k=fact(i)
    i=i+2
    s=s+p/k
    j=j+1
print("sum= ",s)


enter value of n:7
enter value of x:1
sum=  1.175201193643034


iii.	Write a function to obtain sum n terms of the following series for any positive integer value of X 
1+x/1!+x2/2!+x3/3!+…


In [0]:
def fact(num):
    f=1
    for s in range (1,num+1):
        f=f*s
    return f
    
n=int(input("enter value of n:"))
x= int(input("enter value of x:"))

i=1
s=0
j=1
while j<=n:
    p=pow(x,i)
    k=fact(i)
    i=i+1
    s=1+p/k
    j=j+1
print("sum= ",s)


enter value of n:7
enter value of x:1
sum=  1.0001984126984127


iv.	Write a program to multiply two numbers by repeated addition e.g. 
     6*7 = 6+6+6+6+6+6+6


In [0]:
a=int(input("enter first number"))
b= int(input("enter second number"))
f=0
for i in range(1, b+1):
    f=f+a
print(f)
6


enter first number7
enter second number6
42


6

v.	Write a program to compute the wages of a daily laborer as per the following rules :- 
Hours Worked Rate Applicable 
Upto first 8 hrs Rs100/- 
a)	For next 4 hrs Rs30/- per hr extra
b)	For next 4 hrs Rs40/- per hr extra 
c)	For next 4 hrs Rs50/- per hr extra 
d)	For rest Rs60/- per hr extra 
vi.	Accept the name of the labourer and no. of hours worked. Calculate and display the wages. The program should run for N number of labourers as specified by the user.


In [0]:
def main():
    initWage=100
    name=input("Enter Name of Employee:")
    hours=int(input("Enter total hours worked:"))
    if hours<=8:
        totalWage = initWage
        print(totalWage)
    elif(hours>8 and hours<=12):
        tempHour = hours-8
        tempWage = tempHour*30
        totalWage = tempWage + initWage
        print(totalWage)
    
    elif(hours>12 and hours<=16):
        tempHour = hours-12
        tempWage = 4*30
        totalWage = initWage + tempWage + (tempHour*40)
        print(totalWage)

    
    elif(hours>16 and hours<=20):
        tempHour = hours-16
        tempWage = (4*30) + (4*40)
        totalWage = initWage + tempWage + (tempHour*50)
        print(totalWage)

    
    elif(hours>20 and hours<=24):
        print("hello")
        tempHour = hours-20
        tempWage = (4*30) + (4*40) + (4*50)
        totalWage = initWage + tempWage + (tempHour*60)
        print(totalWage)
    
    else:
        print("A single day only has 24 hours.")
        
    
n=int(input("enter no of labourers"))

for i in range(n):
    main()


enter no of labourers2
Enter Name of Employee:aa
Enter total hours worked:7
100
Enter Name of Employee:ss
Enter total hours worked:21
hello
640



vii.	Write a function that takes a string as parameter and returns a string with every successive repetitive character replaced by ? e.g. school may become scho?l.


In [0]:
s=input("enter a string")
ss=list(s)
n=len(ss)

if(n<2):
    print("no of characters too less")

for i in range(n-1):
    if (ss[i]==ss[i+1]):
        ss[i+1]="?"


str="".join(ss) 
print(str)


enter a stringschool is veery far
scho?l is ve?ry far


viii.	Write a program that takes in a sentence as input and displays the number of words, number of capital letters, no. of small letters and number of special symbols.

In [0]:
def Count(str): 
    x = str.split()
    upper, lower, number, special = 0, 0, 0, 0
    for i in range(len(str)): 
        if str[i] >= 'A' and str[i] <= 'Z': 
            upper += 1
        elif str[i] >= 'a' and str[i] <= 'z': 
            lower += 1
        elif str[i] >= '0' and str[i] <= '9': 
            number += 1
        else: 
            special += 1
    print('No of words:', len(x)) 
    print('Upper case letters:', upper) 
    print('Lower case letters:', lower) 
    print('Number:', number) 
    print('Special characters:', special) 
  

str = input("enter a string")
Count(str)


enter a stringwelcome to NIELIT chandigarh
No of words: 4
Upper case letters: 6
Lower case letters: 19
Number: 0
Special characters: 3


ix.	Write a Python program that takes list of numbers as input from the user and produces a cumulative list where each element in the list at any position n is sum of all elements at positions upto n-1

In [0]:
a=[]
n= int(input("Enter the number of elements in list:"))
for x in range(0,n):
    element=int(input("Enter element:"))
    a.append(element)
b=[sum(a[0:x+1]) for x in range(0,len(a))]
print("The original list is: ",a)
print("The new list is: ",b)


Enter the number of elements in list:5
Enter element:11
Enter element:2
Enter element:10
Enter element:1
Enter element:5
The original list is:  [11, 2, 10, 1, 5]
The new list is:  [11, 13, 23, 24, 29]


x.	Write a program which takes list of numbers as input and finds:
a)	The largest number in the list
b)	The smallest number in the list
c)	Product of all the items in the list


In [0]:
list1 = [] 
  
# asking number of elements to put in list 
num = int(input("Enter number of elements in list: ")) 
  
for i in range(1, num + 1): 
    elements = int(input("Enter elements: ")) 
    list1.append(elements) 
      
# print maximum element 
print("Largest element is:", max(list1))


Enter number of elements in list: 5
Enter elements: 1
Enter elements: 2
Enter elements: 3
Enter elements: 4
Enter elements: 5
Largest element is: 5


In [0]:
list1 = [] 
  
# asking number of elements to put in list 
num = int(input("Enter number of elements in list: ")) 
  
# iterating till num to append elements in list 
for i in range(1, num + 1): 
    ele = int(input("Enter elements: ")) 
    list1.append(ele) 
      
# print maximum element 
print("Smallest element is:", min(list1))


Enter number of elements in list: 2
Enter elements: 10
Enter elements: 3
Smallest element is: 3


In [0]:
def multiply(myList): 
  result = 1
  for x in myList: 
    result = result * x  
  return result  
      
list1 = [1, 2, 3]  
list2 = [3, 2, 4] 
print(multiply(list1)) 
print(multiply(list2))


6
24


xi.	Write a Python function that takes two lists and returns True if they have at least one common item

In [0]:
def common_item(list1, list2):
     result = False
     for x in list1:
         for y in list2:
             if x == y:
                 result = True
                 return result
print(common_item([1,2,3,4,5], [5,4,7,8,9]))
print(common_item([1,2,3,4,5], [6,7,8,9]))


True
None


xii.	Write a Python program to combine two dictionary adding values for common keys. 
d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}
Sample output: Counter({'a': 400, 'b': 400, 'd': 400, 'c': 300})


In [0]:
from collections import Counter
d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}
d = Counter(d1) + Counter(d2)
print(d)


Counter({'a': 400, 'b': 400, 'd': 400, 'c': 300})


xiii.	Write a program that takes sentence as input from the user and computes the frequency of each letter. Use a variable of dictionary type to maintain and show the frequency of each letter

In [0]:
def histogram(s):
    d=dict()
    for c in s:
        if c not in d:
            d[c]=1
        else:
            d[c]=d[c]+1
    return d
def main():
    str=input("Enter a string")
    hist=histogram(str)
    print(hist)
    
main()


Enter a stringwelcome to NIELIT
{'w': 1, 'e': 2, 'l': 1, 'c': 1, 'o': 2, 'm': 1, ' ': 2, 't': 1, 'N': 1, 'I': 2, 'E': 1, 'L': 1, 'T': 1}


xiv.	Apply recursive call to do the following: 
a)	Product of two numbers using repetitive addition


In [0]:
def product( x , y ): 
    # if x is less than y, swap  the numbers 
    if x < y: 
        return product(y, x) 
      
    # iteratively calculate y times sum of x 
    elif y != 0: 
        return (x + product (x, y - 1)) 
      
    # if any of the two numbers is zero return zero 
    else: 
        return 0
  
x = 5
y = 2
print( product(x, y))


10


b)	Print fibonacci series upto tem n

In [0]:
def main():
    a=0
    b=1
    print("Enter the number of element in the series: ")
    n=int(input("Enter value of n"))
    print("Fibonacci series is \n");
    fibo(a,b,n)


def fibo(a,b,n):
    if n!=0:
        print(a)
        fibo(b,a+b,n-1)

main()


Enter the number of element in the series: 
Enter value of n10
Fibonacci series is 

0
1
1
2
3
5
8
13
21
34


xv.	Write a program to input two numbers as input and compute the greatest common divisor

In [0]:
a = float(input(" Please Enter the First Value a: "))
b = float(input(" Please Enter the Second Value b: "))

i = 1
while(i <= a and i <= b):
    if(a % i == 0 and b % i == 0):
        gcd = i
    i = i + 1
    
print("\n HCF of {0} and {1} = {2}".format(a, b, gcd))


 Please Enter the First Value a: 54
 Please Enter the Second Value b: 24

 HCF of 54.0 and 24.0 = 6


In [0]:
def gcd(a,b):
    if(b==0):
        return a
    else:
        return gcd(b,a%b)
a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
GCD=gcd(a,b)
print("GCD is: ")
print(GCD)


Enter first number:54
Enter second number:24
GCD is: 
6


xvi.	Write a function that takes two filenames f1 and f2 as input. The function should read the contents of f1 line by line and write them onto f2.

In [0]:
file1= input (“Enter first filename”)
file2= input (“Enter second filename”)

with open (file1, “r”) as f:
	with open (file2, "w") as f1:
		for line in f:
			f1.write(line)


xix.	Write a NumPy program to find the most frequent value in an array.

In [0]:
import numpy as np
a = np.array([1,2,3,1,2,1,1,1,3,2,2,1])
counts = np.bincount(a)
print (np.argmax(counts))


1


In [0]:
import numpy as np
def mostFrequent(arr, n): 
  
    # Sort the array 
    arr.sort() 
  
    # find the max frequency using 
    # linear traversal 
    max_count = 1; res = arr[0]; curr_count = 1
      
    for i in range(1, n):  
        if (arr[i] == arr[i - 1]): 
            curr_count += 1
              
        else : 
            if (curr_count > max_count):  
                max_count = curr_count 
                res = arr[i - 1] 
              
            curr_count = 1
      
    # If last element is most frequent 
    if (curr_count > max_count): 
      
        max_count = curr_count 
        res = arr[n - 1] 
      
    return res 
  
arr=np.array([23, 23, 12, 12, 3, 23, 1,23,45,66])
n = len(arr) 
print (mostFrequent(arr, n))


23


xx.	Take two NumPy arrays having two dimensions. Concatenate the arrays on axis 1.

In [0]:
import numpy as np

array = np.arange(9)
array2D_1 = array.reshape((3,3))
array2D_2 = np.arange(10,19).reshape(3,3)
print(array2D_1)
print(array2D_2)

np.concatenate((array2D_1,array2D_2),axis=1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

xvii.	Write a function that reads the contents of the file f3.txt and counts the number of alphabets, blank spaces, lowercase letters, number of words starting with a vowel and number of occurrences of a work “hello””

In [0]:
def Count(str): 
    x = str.split()
    upper,lower, blank, special,vowels,wvowel, chello  = 0, 0, 0, 0, 0, 0, 0
    for i in range(len(str)): 
        if str[i] >= 'A' and str[i] <= 'Z': 
            upper += 1
        elif str[i] >= 'a' and str[i] <= 'z':
            lower +=1
       
        elif ord(str[i]) == 32:
            blank+=1
        else: 
            special += 1
    for j in x:
      flag=0
      for i in j:
        if(i=='a' or i=='e' or i=='i' or i=='o' or i=='u' or i=='A' or i=='E' or i=='I' or i=='O' or i=='U'):
            vowels=vowels+1
            flag=1
      if flag==1:
        wvowel+=1
    
    for t in x:
      if t=="Hello":
        chello +=1
    alphabets= upper+lower  
    print('alphabets:', alphabets) 
    print('Lower case letters:', lower) 
    print('Blank spaces:', blank) 
    print('Words with Vowels:', wvowel) 
    print('Words with Hello:', chello) 
  
with open ('abc.txt','r') as f:
contents=f.read()
Count(contents)

alphabets: 37
Lower case letters: 34
Blank spaces: 6
Words with Vowels: 5
Words with Hello: 2
