## File Handling and Processing

In [ ]:
import numpy as np 
url = "https://raw.githubusercontent.com/sarwansingh/Python/master/ClassExamples/data/Advertising.csv"


In [ ]:
advtData = np.genfromtxt(url , delimiter=',' , dtype='float')
print(advtData.shape)
print(type(advtData))
print(advtData[:5] )
header = ["TV","Radio","Newspaper","Sales"]
print(header)

(201, 5)
<class 'numpy.ndarray'>
[[  nan   nan   nan   nan   nan]
 [  nan 230.1  37.8  69.2  22.1]
 [  nan  44.5  39.3  45.1  10.4]
 [  nan  17.2  45.9  69.3   9.3]
 [  nan 151.5  41.3  58.5  18.5]]
['TV', 'Radio', 'Newspaper', 'Sales']


In [ ]:
#print(advtData[1:, 1:] ) 
#remove first row and first column 
advtData = advtData[1:,1:]


['TV', 'Radio', 'Newspaper', 'Sales'] [[230.1  37.8  69.2  22.1]
 [ 44.5  39.3  45.1  10.4]
 [ 17.2  45.9  69.3   9.3]
 [151.5  41.3  58.5  18.5]
 [180.8  10.8  58.4  12.9]]


In [ ]:
print(header ,"\n",advtData[:5])

['TV', 'Radio', 'Newspaper', 'Sales'] 
 [[230.1  37.8  69.2  22.1]
 [ 44.5  39.3  45.1  10.4]
 [ 17.2  45.9  69.3   9.3]
 [151.5  41.3  58.5  18.5]
 [180.8  10.8  58.4  12.9]]


In [ ]:
# Display the record with maximum sales and its expenditure on TV 

#record with maximum sale 
#print(advtData[3:].max())
print(advtData[:,3].max())

#show all records having sales as 27.0
#print(advtData[:,3]>=27.0)
print(advtData [advtData[:,3]>=27.0])

27.0
[[276.9  48.9  41.8  27. ]]


In [ ]:
#display all records having sales > 15 and sales <20
print(advtData [(advtData[:,3]>15.0)  & (advtData[:,3]<20.0) ])

[[151.5  41.3  58.5  18.5]
 [214.7  24.    4.   17.4]
 [204.1  32.9  46.   19. ]
 [218.4  27.7  53.4  18. ]
 [228.3  16.9  26.2  15.5]
 [240.1  16.7  22.9  15.9]
 [248.8  27.1  22.9  18.9]
 [265.6  20.    0.3  17.4]
 [202.5  22.3  31.6  16.6]
 [177.   33.4  38.7  17.1]
 [210.7  29.5   9.3  18.4]
 [239.3  15.5  27.3  15.7]
 [131.1  42.8  28.9  18. ]
 [237.4  27.5  11.   18.9]
 [199.1  30.6  38.7  18.3]
 [213.4  24.6  13.1  17. ]
 [193.2  18.4  65.7  15.2]
 [110.7  40.6  63.2  16. ]
 [109.8  47.8  51.4  16.7]
 [217.7  33.5  59.   19.4]
 [163.3  31.6  52.9  16.9]
 [184.9  21.   22.   15.5]
 [135.2  41.7  45.9  17.2]
 [137.9  46.4  59.   19.2]
 [255.4  26.9   5.5  19.8]
 [209.6  20.6  10.7  15.9]
 [125.7  36.9  79.2  15.9]
 [141.3  26.8  46.2  15.5]
 [123.1  34.6  12.4  15.2]
 [229.5  32.3  74.2  19.7]
 [219.8  33.5  45.1  19.6]
 [193.7  35.4  75.6  19.2]
 [280.7  13.9  37.   16.1]
 [197.6  23.3  14.2  16.6]
 [171.3  39.7  37.7  19. ]
 [187.8  21.1   9.5  15.6]
 [ 93.9  43.5  50.5  15.3]
 

In [ ]:

#print(advtData[:,3]>=20.0)
a = np.arange(10)
print(a)

  
np.where(a < 5, a,a*10)

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [ ]:
# effect of top 10 , companies having max expenditure on TV
# effect of mean expenditure on sales.
# normalise the expenditer on TV, Radio and newspaper

In [ ]:
#selecting records from numpy array
x = np.arange(10) 
print(x)
condlist = [x<3, x>5] 
choicelist = [x, x**2] 
np.select(condlist, choicelist )

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2, -9, -9, -9, 36, 49, 64, 81])

## Numpy excercise

#### 1. Create an array from 0 to 26 assign it to a variable x

#### 2. Reverse the order of the array and print it out

####3. Convert the 1-dimensional array you created into a 3 dimensional array

#### 4. Find the index (location) for value 12

In [35]:
arr = np.array([34,56,78,12,45,79,23,44,66,99,32,12,56])
print (arr)
np.where( arr==12 )

[34 56 78 12 45 79 23 44 66 99 32 12 56]


(array([ 3, 11]),)

####5. Create a random shuffled list of values from 0-19 and assign it to variable y

####6. Create an array of boolean values for values in y that are greater than 10

#### 7.Create a random sample of 20 data points from a normal distribution with mean of 10 and standard deviation 5

## Excercises IRIS

####1. 5th and 95th percentile of iris's sepallength

In [30]:
#Hint
arr = np.array([20,5,10,35,25])  # 5,10,20,25,35
print (arr)
print( np.percentile(arr,50))
print( np.percentile(arr,25))
print( np.percentile(arr,0))
np.percentile()
#np.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)
np.percentile(arr, q=[25, 75])

[20  5 10 35 25]
20.0
10.0
5.0


array([10., 25.])

####2. Filter the rows of iris 2D array that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

####3. Show the rows of iris 2D array that does not have any nan value

#### 4. Select the rows of iris 2D array that has any null values

#### 5. In an iris 2D array replace all missing values with 0

####6. count  unique values in iris 2D array

#### 7. Create a bin/categories in new column, on the basis of petal length (3rd column) according to the following criteria : 

Less than 3 --> 'small'

3-5 --> 'medium'

'>=5 --> 'large'



#### 8. Create a new column Volume in the existing 2D array of Iris dataset {formula: volume = (pi x petallength x sepal_length^2)/3 } 

#### 9. Create a random sample from Iris dataset, where virginca is twice in number as compare to versicolor and setosa. 

Hint : setosa-50, virginca-50, versicolor-50

eg. vir-10, versi-5, setosa-5

#### 10. Select top 10 records according to petal length size 

In [3]:
import numpy as np 
url = "https://raw.githubusercontent.com/sarwansingh/Python/master/ClassExamples/data/iris.csv"
irisData = np.genfromtxt(url , delimiter=',' , dtype='float')
print(irisData.shape)
print(irisData[:5,:])

(150, 5)
[[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]]


In [5]:
#extract first column from irisData
print(irisData[:,0])

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [6]:
arr = np.array([2,4,7,9,2,5,1,0,9])
print(arr)

[2 4 7 9 2 5 1 0 9]


In [18]:
np.sort(arr)
arr1= np.sort(irisData[:,0])
print(arr1)
print(arr1 [:-1]) #display all the element except last element
print(arr1 [::-1])  #display all the element in reverse order

[4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.8 4.8 4.9 4.9
 4.9 4.9 4.9 4.9 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.1 5.1 5.1 5.1
 5.1 5.1 5.1 5.1 5.1 5.2 5.2 5.2 5.2 5.3 5.4 5.4 5.4 5.4 5.4 5.4 5.5 5.5
 5.5 5.5 5.5 5.5 5.5 5.6 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7 5.7 5.7 5.7 5.7
 5.7 5.8 5.8 5.8 5.8 5.8 5.8 5.8 5.9 5.9 5.9 6.  6.  6.  6.  6.  6.  6.1
 6.1 6.1 6.1 6.1 6.1 6.2 6.2 6.2 6.2 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3
 6.4 6.4 6.4 6.4 6.4 6.4 6.4 6.5 6.5 6.5 6.5 6.5 6.6 6.6 6.7 6.7 6.7 6.7
 6.7 6.7 6.7 6.7 6.8 6.8 6.8 6.9 6.9 6.9 6.9 7.  7.1 7.2 7.2 7.2 7.3 7.4
 7.6 7.7 7.7 7.7 7.7 7.9]
[4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.8 4.8 4.9 4.9
 4.9 4.9 4.9 4.9 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.1 5.1 5.1 5.1
 5.1 5.1 5.1 5.1 5.1 5.2 5.2 5.2 5.2 5.3 5.4 5.4 5.4 5.4 5.4 5.4 5.5 5.5
 5.5 5.5 5.5 5.5 5.5 5.6 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7 5.7 5.7 5.7 5.7
 5.7 5.8 5.8 5.8 5.8 5.8 5.8 5.8 5.9 5.9 5.9 6.  6.  6.  6.  6.  6.  6.1
 6.1 6.1 6.1 6.1 6.1 6.2 

In [23]:
#arr2 = arr1 [::-1]
#print(arr2[:10])
print(arr1 [::-1][:10])
#print(np.sort(irisData[:,0])[::-1][:10]  )

[7.9 7.7 7.7 7.7 7.7 7.6 7.4 7.3 7.2 7.2]
[4.4 4.2 4.1 4.  3.9 3.9 3.8 3.8 3.8 3.8]


## Other Topics

#### One Hot encoding

In [ ]:
import numpy as np

#count of student w.r.t to total elective subjects taken by them 
studentEsub = [ 2,3,1,4,2,2,3,1,4,2,2,3,3,4,1,1,1,2]
print(studentEsub)

[2, 3, 1, 4, 2, 2, 3, 1, 4, 2, 2, 3, 3, 4, 1, 1, 1, 2]


In [ ]:
output =>   1  2  3 4 
            0  1  0 0
            0  0  1 0

In [ ]:
#res = np.zeros((4,4) ) 
print(len(studentEsub))
res = np.zeros((len(studentEsub),4) ) 
print (res)

18
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
rowId=0
for i in studentEsub:
  res[rowId,i-1]=1
  #print (i)
  rowId+=1
print(studentEsub)
print(res)

[2, 3, 1, 4, 2, 2, 3, 1, 4, 2, 2, 3, 3, 4, 1, 1, 1, 2]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
