In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,3,5.5,7])
 
#array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

In [ ]:
print(arr1)
print(arr1.dtype)
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)

[1.  3.  5.5 7. ]
float64
(4,)
4
1


In [ ]:
arr2 = np.array(
     [ [1,3,5,7] ,
       [11,13,15,17]
     ]
      )

In [ ]:
print(arr2)
print(arr2.dtype)
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)

[[ 1  3  5  7]
 [11 13 15 17]]
int64
(2, 4)
8
2


In [ ]:
print( np.zeros((2,4))   )
print( np.ones( (2,2))  )

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
arr3 = np.arange(5)
arr3 = np.arange(5,15)
arr3 = np.arange(15,5,-2) 
print(arr3)

[15 13 11  9  7]


In [ ]:
#Multi step 
arr4 = np.arange(10)
arr4 = arr4.reshape(2,5)
print(arr4)

#single step 
arr4 = np.arange(10).reshape(2,5)
print(arr4)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Basic Operators

In [ ]:
A  = np.arange(4).reshape(2,2)
print(A)

B = np.array ( [ [4,5],[6,7]])
print(B)

print (" A+B \n", A+B)
A+=B
print(A )

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
 A+B 
 [[ 4  6]
 [ 8 10]]
[[ 4  6]
 [ 8 10]]


In [ ]:
print(A)
print( B)
#print(B*2)
print(A*B)
print(A.dot(B))

[[ 4  6]
 [ 8 10]]
[[4 5]
 [6 7]]
[[16 30]
 [48 70]]
[[ 52  62]
 [ 92 110]]


In [ ]:
stuData = np.array ( 
    # rollno, marks_Eng, marks_Hindi, marks_maths
    [[ 1, 70,68,88],
     [ 2, 56,88,78],
     [ 3, 56,67,79]]
)
print( stuData)

[[ 1 70 68 88]
 [ 2 56 88 78]
 [ 3 56 67 79]]


In [ ]:
print(stuData.max())
print(stuData.min())
print(stuData.mean())
print(stuData.sum())

88
1
54.666666666666664
656


In [ ]:
print(stuData.sum(1))

[227 224 205]


In [ ]:
# slice the array to get marks only
print(stuData)
print( stuData[0:,1:])
#total marks for each student
print( stuData[0:,1:].sum(1))
#highest marks by each student
print( stuData[0:,1:].max(1))

[[ 1 70 68 88]
 [ 2 56 88 78]
 [ 3 56 67 79]]
[[70 68 88]
 [56 88 78]
 [56 67 79]]
[226 222 202]
[88 88 79]


In [ ]:
# rollno and total marks for each student
#rollno of students
print(stuData[:,0])
#total marks for each student
print( stuData[0:,1:].sum(1))

print(stuData[:,0].reshape(3,1) ) #+  stuData[0:,1:].sum(1).reshape(3,1) )

[1 2 3]
[226 222 202]
[[1]
 [2]
 [3]]


### Universal function

In [ ]:
print(A)

[[ 4  6]
 [ 8 10]]


In [ ]:
A**2


array([[ 16,  36],
       [ 64, 100]])

In [ ]:
np.sqrt(A)

array([[2.        , 2.44948974],
       [2.82842712, 3.16227766]])

In [ ]:
np.add(A,B)

array([[ 8, 11],
       [14, 17]])

In [ ]:
print(A[-2])

[4 6]


In [ ]:
A1 = np.arange(24).reshape(6,4)
print(A1)
print(A1[0,0] , A1[5,3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
0 23


In [ ]:
A2 = np.arange(24).reshape(2,3,4)
print(A2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print(A2 [ 0,:,:])
print(A2 [ 0,1,:])  # first 2D array and second row
print(A2 [0,1,2])
print(A2 [0,1,1:3])
print(A2 [ 0,...])
print(A2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
6
[5 6]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print(A2.shape , A2.ndim)

print(A1.shape, A1.ndim)

(2, 3, 4) 3
(6, 4) 2


## Broadcasting


In [ ]:
import numpy as np

A = np.arange( 6).reshape(3,2)
print(A.ndim,A.shape)
print(A)
B = np.array([4,8])
print(B.ndim)
print(B,B.shape)

2 (3, 2)
[[0 1]
 [2 3]
 [4 5]]
1
[4 8] (2,)


In [ ]:
print(A+B)
#2 new rows are added in B by boardcasting

[[ 4  9]
 [ 6 11]
 [ 8 13]]


In [ ]:
C = np.array([4,8,2]).T
print(C.ndim, C.shape, C)
D = C.reshape(3,1)
print(D.ndim, D.shape, D)

1 (3,) [4 8 2]
2 (3, 1) [[4]
 [8]
 [2]]


In [ ]:
print(A,"\nD: \n" , D," \n A+D : \n", A+D)
#a new column is added by broadcasting

[[0 1]
 [2 3]
 [4 5]] 
D: 
 [[4]
 [8]
 [2]]  
 A+D : 
 [[ 4  5]
 [10 11]
 [ 6  7]]


## computational efficiency

In [ ]:
def compute_reciprocal(values) : 
	output = np.empty(len(values))
	for i in range(len(values)):
		output[i] = 1.0/values[i]
	return output

In [ ]:
v1 = np.random.randint(10,100, size=5)
print(v1)

[45 39 78 66 65]


In [ ]:
print(compute_reciprocal(v1))

[0.02222222 0.02564103 0.01282051 0.01515152 0.01538462]


In [ ]:
%timeit compute_reciprocal(v1)

The slowest run took 4.92 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 13 µs per loop


In [ ]:
%timeit 1/v1

The slowest run took 27.10 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.64 µs per loop


In [ ]:
bigv1 = np.random.randint(1,100, size=100000)
%timeit compute_reciprocal(bigv1) # the simple way in which all languagues does

1 loop, best of 3: 229 ms per loop


In [ ]:
%timeit (1.0/bigv1) # the way numpy does

1000 loops, best of 3: 297 µs per loop


## Reading file in Numpy


In [1]:
import numpy as np
url = "https://raw.githubusercontent.com/sarwansingh/Python/master/ClassExamples/data/iris.csv"

In [17]:
iris = np.genfromtxt(url, delimiter=',', dtype='float')
#np.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, 
#skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, 
#usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>...", replace_space='_', autostrip=False, 
#case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, 
#invalid_raise=True, max_rows=None, encoding='bytes')
names = ['sepallength', 'sepalwidth' , 'petallength' , 'petalwidth' , 'species']
print(type(iris))
print(iris.shape)
print(names)
#print(iris[:5])
#print(iris[48:53])
#print(iris[98:103])
#print(iris[:,0])  # all the rows in column 1
print("Maximum value of sepal length " ,iris[:,0].max(), iris[:,0].min())
print("Maximum value of sepal width  " ,iris[:,1].max(), iris[:,1].min())

<class 'numpy.ndarray'>
(150, 5)
['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species']
Maximum value of sepal length  7.9 4.3
Maximum value of sepal width   4.4 2.0


In [24]:
print(iris[:5,:])
iris5 = iris[:5,0]

[[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]]


In [34]:
smin= 4.3 ; smax=7.9
print(smin, smax)
print( (iris5[0]-smin)/(smax-smin))
print( (iris5[1]-smin)/(smax-smin))
print( (7.9-smin)/(smax-smin))
print( (4.3-smin)/(smax-smin))
print(iris5)
print(( iris5-smin)/(smax-smin))
print(( iris[:,0]-smin)/(smax-smin))

4.3 7.9
0.22222222222222213
0.1666666666666668
1.0
0.0
[5.1 4.9 4.7 4.6 5. ]
[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444]
[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222