# Building the ML Model 

In [1]:
#import packages 
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
 
import pickle
import warnings
warnings.filterwarnings("ignore")

In [3]:
#https://raw.githubusercontent.com/sarwansingh/Python/master/ClassExamples/data/student-pass-fail-data.csv
data = pd.read_csv("student-pass-fail-data.csv")
data = np.array(data)
print(len(data))
print(data[:5])

1000
[[ 7 27  1]
 [ 2 43  0]
 [ 7 26  1]
 [ 8 29  1]
 [ 3 42  0]]


In [4]:
# extract the input matrix from data in X
X = data[:, 0:-1]
# extract the labels in y 
y = data[:, -1]
#casting the entire data into int
y = y.astype('int')
X = X.astype('int')

print("Rows in X " , len(X) , " \nRows in y ", len(y))
print(X[:5],y[:5])


Rows in X  1000  
Rows in y  1000
[[ 7 27]
 [ 2 43]
 [ 7 26]
 [ 8 29]
 [ 3 42]] [1 0 1 1 0]


In [5]:
#build the logisticRegression model
log_reg = LogisticRegression()
# fit the model with data
log_reg.fit(X,y)

LogisticRegression()

In [6]:
#testing the build model 
test=[[ 7,27]]
print(test)

print(log_reg.predict_proba(test))
print(log_reg.predict(test))  # pass
print(log_reg.predict([[2,43]])) #fail

[[7, 27]]
[[ 0.12276493  0.87723507]]
[1]
[0]


In [7]:
# Saving model to disk
#Serialization  - saving the state (in memory) to file (on disk)
pickle.dump(log_reg,open('model.pkl','wb'))

# Loading model to compare the results
#Deserialization  - reteriving  the file (on disk) to memory (RAM)
model=pickle.load(open('model.pkl','rb'))
print(model.predict_proba([[7,43]]))
print(model.predict([[7,27]]))

[[  9.99990993e-01   9.00739994e-06]]
[1]


## use the model and display in Flask

In [ ]:
#app.py
from flask import Flask,request, url_for, redirect, render_template
import pickle
import numpy as np

app = Flask(__name__)
model=pickle.load(open('model.pkl','rb'))

@app.route('/')
def home():
    return render_template("index.html")

@app.route('/predict',methods=['POST','GET'])
def predict():
    # receive the values send by user in three text boxes thru request object -> requesst.form.values()
    
    int_features = [int(x) for x in request.form.values()]
    final_features = [np.array(int_features)]
    #print(final_features)
    #prediction = model.predict(final_features)
    #output = round(prediction[0], 2)
    
    prediction=model.predict_proba(final_features)
    output='{0:.{1}f}'.format(prediction[0][1], 2)
   
    #print(output )

    return render_template('index.html', pred='Student passing probability is :  {}'.format(output))

if __name__ == '__main__':
    app.run(debug=False)


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Aug/2020 15:27:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Aug/2020 15:27:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Aug/2020 15:28:21] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [28/Aug/2020 15:28:29] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [28/Aug/2020 15:28:42] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [28/Aug/2020 15:28:57] "POST /predict HTTP/1.1" 200 -
