In [5]:
import csv
import numpy as np

def read_csv(x):
    string_data = open(x).read()
    string_list = string_data.split("\n")[1:]
    final_list = []
    
    for row in string_list:
        string_fields = row.split(";")
        int_fields = []
        for value in string_fields:
            int_fields.append((value))
        final_list.append(int_fields)
    return final_list

winelist = read_csv("winequality-red.csv")
winelist

[['7.4',
  '0.7',
  '0',
  '1.9',
  '0.076',
  '11',
  '34',
  '0.9978',
  '3.51',
  '0.56',
  '9.4',
  '5'],
 ['7.8',
  '0.88',
  '0',
  '2.6',
  '0.098',
  '25',
  '67',
  '0.9968',
  '3.2',
  '0.68',
  '9.8',
  '5'],
 ['7.8',
  '0.76',
  '0.04',
  '2.3',
  '0.092',
  '15',
  '54',
  '0.997',
  '3.26',
  '0.65',
  '9.8',
  '5'],
 ['11.2',
  '0.28',
  '0.56',
  '1.9',
  '0.075',
  '17',
  '60',
  '0.998',
  '3.16',
  '0.58',
  '9.8',
  '6'],
 ['7.4',
  '0.7',
  '0',
  '1.9',
  '0.076',
  '11',
  '34',
  '0.9978',
  '3.51',
  '0.56',
  '9.4',
  '5'],
 ['7.4',
  '0.66',
  '0',
  '1.8',
  '0.075',
  '13',
  '40',
  '0.9978',
  '3.51',
  '0.56',
  '9.4',
  '5'],
 ['7.9',
  '0.6',
  '0.06',
  '1.6',
  '0.069',
  '15',
  '59',
  '0.9964',
  '3.3',
  '0.46',
  '9.4',
  '5'],
 ['7.3',
  '0.65',
  '0',
  '1.2',
  '0.065',
  '15',
  '21',
  '0.9946',
  '3.39',
  '0.47',
  '10',
  '7'],
 ['7.8',
  '0.58',
  '0.02',
  '2',
  '0.073',
  '9',
  '18',
  '0.9968',
  '3.36',
  '0.57',
  '9.5',
  '7'],

In [7]:
np.shape(winelist)

(1600,)

In [15]:
import numpy as np
wines=np.genfromtxt("winequality-red.csv", delimiter=";"  ,skip_header=1)
wines

array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [10]:
np.shape(wines)

(1599, 12)

AttributeError: 'list' object has no attribute 'head'

In [11]:
#add the quality column to itself,
wines[:,11] + wines[:,11]

array([ 10.,  10.,  10., ...,  12.,  10.,  12.])

In [20]:
#multiply alcohol by quality, and select the wine with the highest score:
a=np.array(wines[:,10] * wines[:,11])
print(a)
print(a.max())
print(a.min())

[49.  49.  58.8 ... 66.  51.  66. ]
112.0
25.200000000000003


In [22]:
#broadcasting
rand_array = np.random.rand(12)
r=wines + rand_array
print(r)


[[ 8.75331839  1.17844785  0.20356379 ...  0.74219007 10.41487018
   5.40485797]
 [ 8.75331839  1.05844785  0.24356379 ...  0.71219007 10.41487018
   5.40485797]
 [12.15331839  0.57844785  0.76356379 ...  0.64219007 10.41487018
   6.40485797]
 ...
 [ 7.25331839  0.80844785  0.33356379 ...  0.81219007 11.61487018
   6.40485797]
 [ 6.85331839  0.94344785  0.32356379 ...  0.77219007 10.81487018
   5.40485797]
 [ 6.95331839  0.60844785  0.67356379 ...  0.72219007 11.61487018
   6.40485797]]


In [25]:
#sum one column

print(wines[:,11].sum())
#sum all columns
a=wines.sum(axis=0)
print(a)

#check the shape
wines.sum(axis=0).shape


9007.0
[13295.7       843.285     433.29     4057.65      139.783   25373.
 74268.       1592.80014  5290.96     1051.82    16656.95     9007.     ]


(12,)

In [33]:
#with axis=1, sum of each row:
a=np.array(wines.sum(axis=1))
print(a)
#only for two rows
wines[0:2,:].sum(axis=1)



[123.0548   99.699   111.553   ... 100.48174 105.21547  92.49249]


array([123.0548,  99.699 ])

In [36]:
#comparison operators
#to see which wines have a quality rating higher than 5, we can do this:
print(wines[:,11] > 50)

#to see if any wines have a quality rating equal to 10:
wines[:,11] == 10



[False False False ... False False False]


array([False, False, False, ..., False, False, False])

In [56]:
#subsetting
#only select rows in wines where the quality is over 7:

high_quality = wines[:,11] > 7 
print(high_quality)
print("\n\n")
#shows all the rows where the value is true along with all the columns
print
print(wines[high_quality,:])

#further limiting the search
#shows rows 0 to 2 along with all the columns out of true rows selected
wines[high_quality,:][:3,:]


[False False False ... False False False]



[[7.9000e+00 3.5000e-01 4.6000e-01 3.6000e+00 7.8000e-02 1.5000e+01
  3.7000e+01 9.9730e-01 3.3500e+00 8.6000e-01 1.2800e+01 8.0000e+00]
 [1.0300e+01 3.2000e-01 4.5000e-01 6.4000e+00 7.3000e-02 5.0000e+00
  1.3000e+01 9.9760e-01 3.2300e+00 8.2000e-01 1.2600e+01 8.0000e+00]
 [5.6000e+00 8.5000e-01 5.0000e-02 1.4000e+00 4.5000e-02 1.2000e+01
  8.8000e+01 9.9240e-01 3.5600e+00 8.2000e-01 1.2900e+01 8.0000e+00]
 [1.2600e+01 3.1000e-01 7.2000e-01 2.2000e+00 7.2000e-02 6.0000e+00
  2.9000e+01 9.9870e-01 2.8800e+00 8.2000e-01 9.8000e+00 8.0000e+00]
 [1.1300e+01 6.2000e-01 6.7000e-01 5.2000e+00 8.6000e-02 6.0000e+00
  1.9000e+01 9.9880e-01 3.2200e+00 6.9000e-01 1.3400e+01 8.0000e+00]
 [9.4000e+00 3.0000e-01 5.6000e-01 2.8000e+00 8.0000e-02 6.0000e+00
  1.7000e+01 9.9640e-01 3.1500e+00 9.2000e-01 1.1700e+01 8.0000e+00]
 [1.0700e+01 3.5000e-01 5.3000e-01 2.6000e+00 7.0000e-02 5.0000e+00
  1.6000e+01 9.9720e-01 3.1500e+00 6.5000e-01 1.1000e+01 8.0000e+

array([[7.900e+00, 3.500e-01, 4.600e-01, 3.600e+00, 7.800e-02, 1.500e+01,
        3.700e+01, 9.973e-01, 3.350e+00, 8.600e-01, 1.280e+01, 8.000e+00],
       [1.030e+01, 3.200e-01, 4.500e-01, 6.400e+00, 7.300e-02, 5.000e+00,
        1.300e+01, 9.976e-01, 3.230e+00, 8.200e-01, 1.260e+01, 8.000e+00],
       [5.600e+00, 8.500e-01, 5.000e-02, 1.400e+00, 4.500e-02, 1.200e+01,
        8.800e+01, 9.924e-01, 3.560e+00, 8.200e-01, 1.290e+01, 8.000e+00]])

In [59]:
#subseting
#to look for wines with a lot of alcohol and high quality. 

high_quality_and_alcohol = (wines[:,10] > 10) & (wines[:,11] > 7)
wines[high_quality_and_alcohol,10:]
#shows the col 10 and 11 

array([[12.8,  8. ],
       [12.6,  8. ],
       [12.9,  8. ],
       [13.4,  8. ],
       [11.7,  8. ],
       [11. ,  8. ],
       [11. ,  8. ],
       [14. ,  8. ],
       [12.7,  8. ],
       [12.5,  8. ],
       [11.8,  8. ],
       [13.1,  8. ],
       [11.7,  8. ],
       [14. ,  8. ],
       [11.3,  8. ],
       [11.4,  8. ]])

In [63]:
#combining subsetting and assignment to overwrite certain values in an array:

high_quality_and_alcohol = (wines[:,10] > 10) & (wines[:,11] > 7) 
#set value 20 in columns 10 onwards (10th and 11th)
wines[high_quality_and_alcohol,10:] = 20
wines[high_quality_and_alcohol,10:]

array([[20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.],
       [20., 20.]])